name: build-n-test
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - run: dotnet build ./ConsoleApp1.sln
    - run: dotnet test ./ConsoleApp1.sln